version: '3.1'

services:
  counter:
    build: backend
    ports:
     - "8080:8080"
  database:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=admin
  frontend:
    build: frontend
    ports:
     - "8082:8082"