version: '3.1'

services:
#  counter:
#    image: mycounter
#    build:
#      dockerfile: Dockerfile
#    ports:
 #     - "8080:8080"
  database:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=admin